/* This file is auto-generated by tool, DO NOT modify it manully. */

#ifndef CONFIG_BOARDIDS_H
#define CONFIG_BOARDIDS_H

#define BOARD_ID_H882C_VA   32
#define BOARD_ID_Y340_U081_VA   53
#define BOARD_ID_G526_L12_VA   21
#define BOARD_ID_MSM8930   68
#define BOARD_ID_M932_VC   80
#define BOARD_ID_U8955_VA   48
#define BOARD_ID_M932_VB   0
#define BOARD_ID_M932_VA   16
#define BOARD_ID_Y301_A2_VA   96
#define BOARD_ID_G527_U081_VA   85
#define BOARD_ID_U8731_VA   64
#define BOARD_ID_H882C_VB   112
#define BOARD_ID_G526_L13_VA   37
#define BOARD_ID_Y340_U081_VB   101
#define BOARD_ID_G740_L00_VA   117
#define BOARD_ID_G526_L11_VA   5

#endif
