/* This file is auto-generated by tool, please don't manully modify it.*/

#include <hsad/config_boardids.h>

#include "hw_H882C_VA_configs.c"
#include "hw_Y340_U081_VA_configs.c"
#include "hw_G526_L12_VA_configs.c"
#include "hw_MSM8930_configs.c"
#include "hw_M932_VC_configs.c"
#include "hw_U8955_VA_configs.c"
#include "hw_M932_VB_configs.c"
#include "hw_M932_VA_configs.c"
#include "hw_Y301_A2_VA_configs.c"
#include "hw_G527_U081_VA_configs.c"
#include "hw_U8731_VA_configs.c"
#include "hw_H882C_VB_configs.c"
#include "hw_G526_L13_VA_configs.c"
#include "hw_Y340_U081_VB_configs.c"
#include "hw_G740_L00_VA_configs.c"
#include "hw_G526_L11_VA_configs.c"
#ifdef CONFIG_HW_POWER_TREE
extern struct board_id_general_struct config_power_H882C_VA;
extern struct board_id_general_struct config_power_Y340_U081_VA;
extern struct board_id_general_struct config_power_G526_L12_VA;
extern struct board_id_general_struct config_power_MSM8930;
extern struct board_id_general_struct config_power_M932_VC;
extern struct board_id_general_struct config_power_U8955_VA;
extern struct board_id_general_struct config_power_M932_VB;
extern struct board_id_general_struct config_power_M932_VA;
extern struct board_id_general_struct config_power_Y301_A2_VA;
extern struct board_id_general_struct config_power_G527_U081_VA;
extern struct board_id_general_struct config_power_U8731_VA;
extern struct board_id_general_struct config_power_H882C_VB;
extern struct board_id_general_struct config_power_G526_L13_VA;
extern struct board_id_general_struct config_power_Y340_U081_VB;
extern struct board_id_general_struct config_power_G740_L00_VA;
extern struct board_id_general_struct config_power_G526_L11_VA;
#endif

/*gpio perl producted data*/
#ifdef CONFIG_HUAWEI_GPIO_UNITE
extern struct board_id_general_struct config_gpio_H882C_VA;
extern struct board_id_general_struct config_pm_gpio_H882C_VA;
extern struct board_id_general_struct config_gpio_Y340_U081_VA;
extern struct board_id_general_struct config_pm_gpio_Y340_U081_VA;
extern struct board_id_general_struct config_gpio_G526_L12_VA;
extern struct board_id_general_struct config_pm_gpio_G526_L12_VA;
extern struct board_id_general_struct config_gpio_MSM8930;
extern struct board_id_general_struct config_pm_gpio_MSM8930;
extern struct board_id_general_struct config_gpio_M932_VC;
extern struct board_id_general_struct config_pm_gpio_M932_VC;
extern struct board_id_general_struct config_gpio_U8955_VA;
extern struct board_id_general_struct config_pm_gpio_U8955_VA;
extern struct board_id_general_struct config_gpio_M932_VB;
extern struct board_id_general_struct config_pm_gpio_M932_VB;
extern struct board_id_general_struct config_gpio_M932_VA;
extern struct board_id_general_struct config_pm_gpio_M932_VA;
extern struct board_id_general_struct config_gpio_Y301_A2_VA;
extern struct board_id_general_struct config_pm_gpio_Y301_A2_VA;
extern struct board_id_general_struct config_gpio_G527_U081_VA;
extern struct board_id_general_struct config_pm_gpio_G527_U081_VA;
extern struct board_id_general_struct config_gpio_U8731_VA;
extern struct board_id_general_struct config_pm_gpio_U8731_VA;
extern struct board_id_general_struct config_gpio_H882C_VB;
extern struct board_id_general_struct config_pm_gpio_H882C_VB;
extern struct board_id_general_struct config_gpio_G526_L13_VA;
extern struct board_id_general_struct config_pm_gpio_G526_L13_VA;
extern struct board_id_general_struct config_gpio_Y340_U081_VB;
extern struct board_id_general_struct config_pm_gpio_Y340_U081_VB;
extern struct board_id_general_struct config_gpio_G740_L00_VA;
extern struct board_id_general_struct config_pm_gpio_G740_L00_VA;
extern struct board_id_general_struct config_gpio_G526_L11_VA;
extern struct board_id_general_struct config_pm_gpio_G526_L11_VA;
#endif

/*total table*/
struct board_id_general_struct  *hw_ver_total_configs[] = 
{
#ifdef CONFIG_HUAWEI_GPIO_UNITE
    &config_gpio_H882C_VA, //gpio
    &config_gpio_Y340_U081_VA, //gpio
    &config_gpio_G526_L12_VA, //gpio
    &config_gpio_MSM8930, //gpio
    &config_gpio_M932_VC, //gpio
    &config_gpio_U8955_VA, //gpio
    &config_gpio_M932_VB, //gpio
    &config_gpio_M932_VA, //gpio
    &config_gpio_Y301_A2_VA, //gpio
    &config_gpio_G527_U081_VA, //gpio
    &config_gpio_U8731_VA, //gpio
    &config_gpio_H882C_VB, //gpio
    &config_gpio_G526_L13_VA, //gpio
    &config_gpio_Y340_U081_VB, //gpio
    &config_gpio_G740_L00_VA, //gpio
    &config_gpio_G526_L11_VA, //gpio
#endif
#ifdef CONFIG_HUAWEI_GPIO_UNITE
    &config_pm_gpio_H882C_VA, //pm gpio
    &config_pm_gpio_Y340_U081_VA, //pm gpio
    &config_pm_gpio_G526_L12_VA, //pm gpio
    &config_pm_gpio_MSM8930, //pm gpio
    &config_pm_gpio_M932_VC, //pm gpio
    &config_pm_gpio_U8955_VA, //pm gpio
    &config_pm_gpio_M932_VB, //pm gpio
    &config_pm_gpio_M932_VA, //pm gpio
    &config_pm_gpio_Y301_A2_VA, //pm gpio
    &config_pm_gpio_G527_U081_VA, //pm gpio
    &config_pm_gpio_U8731_VA, //pm gpio
    &config_pm_gpio_H882C_VB, //pm gpio
    &config_pm_gpio_G526_L13_VA, //pm gpio
    &config_pm_gpio_Y340_U081_VB, //pm gpio
    &config_pm_gpio_G740_L00_VA, //pm gpio
    &config_pm_gpio_G526_L11_VA, //pm gpio
#endif
    &config_common_H882C_VA, //common xml
    &config_common_Y340_U081_VA, //common xml
    &config_common_G526_L12_VA, //common xml
    &config_common_MSM8930, //common xml
    &config_common_M932_VC, //common xml
    &config_common_U8955_VA, //common xml
    &config_common_M932_VB, //common xml
    &config_common_M932_VA, //common xml
    &config_common_Y301_A2_VA, //common xml
    &config_common_G527_U081_VA, //common xml
    &config_common_U8731_VA, //common xml
    &config_common_H882C_VB, //common xml
    &config_common_G526_L13_VA, //common xml
    &config_common_Y340_U081_VB, //common xml
    &config_common_G740_L00_VA, //common xml
    &config_common_G526_L11_VA, //common xml
#ifdef CONFIG_HW_POWER_TREE
    &config_power_H882C_VA,
    &config_power_Y340_U081_VA,
    &config_power_G526_L12_VA,
    &config_power_MSM8930,
    &config_power_M932_VC,
    &config_power_U8955_VA,
    &config_power_M932_VB,
    &config_power_M932_VA,
    &config_power_Y301_A2_VA,
    &config_power_G527_U081_VA,
    &config_power_U8731_VA,
    &config_power_H882C_VB,
    &config_power_G526_L13_VA,
    &config_power_Y340_U081_VB,
    &config_power_G740_L00_VA,
    &config_power_G526_L11_VA,
#endif
};
